---
production:
  adapter: postgresql
  encoding: unicode
  database: todaycapital_production
  pool: 5
  username: rosscdh
  password:

development:
  adapter: sqlite3
  database: db/development.sqlite3
  username: 
  password: 
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000


test:
  adapter: sqlite3
  database: db/development.sqlite3
  username: 
  password: 
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
